workflows:
  android-capacitor-debug:
    name: Android Capacitor Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20
      groups:
        - google_play # For keystores if needed later, but using debug for now
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Web Project
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
